matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token:
          secure: "GelB6LwE46TvQp5W24+zNPVz9ekaE2lFdjBRZa/pybzMIYdvzg/WUIjwWztjuwDc2OC40fJWUZsth6Za812JoEDwIJe9ajojbr8PIoo6v++4kVRaTYfkbZhLDUNkLw6Z+VO4eKEPdOfbJmAmnI+JJ57f8vO47Ccg2KSRAgaKRaSXaiIICQvKMEDayCzekPHxS8sYgWh5kKZX2BrAS8dTR2jvGN6+K4u+24OdqKyiT7J9KBrqZJUfJyjxf32ZRKQdmovnndMkV5V8/X4mXIFQt9XXYn/gQHgZvoIjsiLsa1nFigpR5/5vJWohDsc3HD1WeG4FJoIb3fSdUXRyf/G+a/22UK1+Nj6KRPEPrXTyBcQa2a03tEaFgJInCI40LKMMp9IKeOTM6Ttf4LThIYLPSf/l2sDleV1A6daJvpTeLD+ZVGFTe7GmkgRycOZS2YAFH4vOdnjTdenEyPDDS0ekPtUZ5kCQlRPoyNOBzTgk7h8b/9gMdc2Z9Nqy3zbLDkZczIfkNYcgOXn3zt5Yle0Ge5PXC2AILRlikSzzlnOcnnkzsx9Nsxapt3HFAXIgyHe9NipWDCTuRFL5GOkshTIEdw06il1DGJ4tYG1qFv+yuJ1SsAuAk0OxNfk4gf/aWuVUvC/N1A5w0t9SR8SwVq8zn3UST8Df4Y/g1rFWEe1pBsA="
    before_install:
    - cd frontend
    install:
    - npm install
    script:
    - "./node_modules/.bin/eslint src/"
    - yarn test --coverage --watchAll=false
    - sonar-scanner
