matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: "swsnu"
        token:
          secure: "G+td0lMn7dZFXvcPv8aJMaXAGna43wSXDwjYoePOOU7rWx8tr7RjLmfmyCVuYPAtbeWEN9ns0ym53mhkS/fqPr9QutvzGLsqg2EPsXHTZpLsoVAv6r1l2MNW6OUJ0Rm5oPbDtLdCRtk8VGJb5iUJYbRveKuc+YyqND+4opzisMH+rkvZL3dFWQ9DZLGPJ1nvMgqSKMzNm+VRDqNNXNbjjd9aZMRWTZpYgVI1HxNTi3pxSIH3U/SnctUIw3TfqWzKOXB9RoQk/6MExjE+e5tN/AlGaTE9AJ8fmS1CiDF2fecyVFlh9WNKs/8bDRkxXOGriIkIyemiwKuPfpLVpGh/wgJIhOZLiw7Z9gvAaKHZVCN/I09swY6bosrpTuMQ5QeZYkzhMb0yB3phaP3suqJyK486c0OH1snYpnAbq3rj4l3F8VeZaqQNw9EmlCypIy9xc/ds2AMH8Ub4eydexirxyTiWLObaQEV8PmnR4LXhyKaXmyWGfoTJopzqfbIso0tx61U6Bzbp9+ek3Dy7eoj8owvqJteDROPo3ALlEPwGN/4k8f3z9Zc+uJjVEcnzpiCTVu/g57N55GKcnJ0mF5mYd8bnXWu04AT8ZkqDqlKVws82aVF9Dat8rnON9eFKwu1ODMsJzm1+POvZ5JT5QOPLk/WFmwYu+qb9xa8+11EYcVU="
    before_install:
    - cd frontend
    install:
    - npm install
    script:
    - "./node_modules/.bin/eslint src/"
    - yarn test --coverage --watchAll=false
    - sonar-scanner
