matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: swsnu
        token:
          secure: "Mmoxlj6jFM3SDtuA8vfdGSdRWz4SjAaKfAXQ2gaofrofwGv7NNBBOrWCBu+sLoDJK6XbxjKh93SR3M8VniXxdSh61+yxg1IA7FyW1oKAUKRmrEAqsNlO9/FqyccUX2XuxYysDlBIjjswRnSK9xaxKkuVQls+XhwWpQKTAGB7eF1H7+9vIfuMK9lhRJNpDd0GfTuFoT88Be0UsbhsBiqyaAO0OV9Ikre/oe8vkPr9NQXDUBL07cGYw+a/XeQr5XaYFFEtfFhC4UXVlfFSw7h3KGcvBDRkzjN5CL8ShFASRoHn3xvpKYF2CRGsC+q9p/b+KwVj5mqSgENwa5GL7TfMoc5bSjBNFBJlAWVxfOJGBwySkiuPSwh3BBhZYo719Whi9qq+SsXzK4fyuHhvjjAwkABDPZ1LhsN8sjh8cUCPA3loS2xO36trzitiw5KKUzd+0l9430fRFg0oiRJprusoNwB3QmLVJlAuJbm6JOQIvMw8oRkWb/ZTQ9RJt8Fc2wW4dJgEx2BYY7S9JtI2qymDgz4oqAUnJnH5BT0Aq06AWFDZJE1Q5wr3XlQSPUS/iIFOAalP0oUf4k2MeLyqozGnkyB5vX4iHGx7V7Hkp6OVjkzj5SfYYjOocCrFAriUmSaSv6Oo5F67ImOBXSrZ8hOFYhLRXN2XPXpLNdrr2d6/YX0="
    before_install:
    - cd frontend
    install:
    - npm install
    script:
    - "./node_modules/.bin/eslint src/"
    - yarn test --coverage --watchAll=false
    - sonar-scanner
