matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: swsnu
        token:
          secure: "Y/obIbLcfOb/v2zEoG3r6vDNERHsyn8mQ/GY+kL07aS9QreSZT8B5RQlms3piTigWTfYfm086UcMk/nqhhYgVXD1a6pm1DjkemP69wUnL2HCWHaN0XnZieGmUIbpTwVYo9EhBkK5+WYAj3xd++6mcU+NeNPmH+vXU06CSW5iPGCEhEbcqVYcGho1S2oRGwL+JZCOlbWmfvAqFFXe+0qny8bGQYc4vTjhbYeOBNoESABj01KW/xtBQTxrL5x/jUVd1tVwM0FhwqrW/78tED/s3wvaoMHJc9bL4ileRSc8XQ4soFpJwM7t9my8wo5KLGtVcaDNb/DIgUclYpjBnUcdXcCAlzmf2/6+JzRv7UEUQZqjTn5yPh4G6lTQeUZdeX5pK0HqCuV9T0bLAAXxA2GnIh75QuWmCNtfytkzJKgZB5lZ4c/yroMhjiENObEpjs/dOfvY8O2eFBM82hRVMmCJ+KqpB2e1wENnPdcV98OKSg4qgBp8MVWQMShqSCgb1in960MGO/uwe/piPGnyiKH4/ksfS4fZg8F9I+Fb9I9LpIxEI6RJFTBjC+tYUqKYHgYvHKZf+U4hohjH44OA/3q6Mr3JVv8e7Hna0U7KfbEcUq2471M+rCEk8Xow/ICJMQl8qPAl05WpvINEsTJ/+hEMataAlbsjL3tCX7/0Wd0ZN3s="
    before_install:
    - cd frontend
    install:
    - npm install
    script:
    - "./node_modules/.bin/eslint src/"
    - yarn test --coverage --watchAll=false
    - sonar-scanner
