matrix:
  include:
  - language: node_js
    node_js:
    - '10'
    dist: trusty
    addons:
      sonarcloud:
        organization: swsnu
        token:
          secure: "WcrRwwmSSmQKBuAGvN8t2IwKyq8vwER1uRVBwQ5z8KBP6SVPS0aWgn+tFX9bisOwD8Qe9+Tpg1OymuPPAkYn+SU27g+JMjKQIGR0eUgjD7nEp2zfJJQe2fs2vJ4OIz7DDxrG9JS3EvN/dykiay3q71OxO+CP0YWKKf/yMkHyDjtWNZDEzXo/vmFZHew9SdgKRqefu/nVE/esxVx3MqUcBpv1kMA5Twe2KzgpRBZAkGynfAhNNHycM6jXTK2vcowIkqtjdkWC7wTvUsHkdWMxQQa37/jl5J/JMVfm2f3fWhq/od2N+tPkubbIahvvUyqqe0Xaw8W6T7qOUJC4/Wza9RkbyD1nhpxe3YhPIb1+FWGzcbgPofRcJ2wpOkbDK7XZhN9CjtbcCV0PcxQefMdpzoOgtNvAzj8hYQ1g2GGgOT9sqOPujr/wAkV4yD7Qs7Lj9fnakMCN7mspZpSQ8PqPVhu02pcfpDJkmued82fgA5xFw0i6YJWWa/aJe+7FMLihE1ZGYW0IZYU+cgV+mLRjwB9FOAWJMqXhVMs8Hj/V3qoNhSEcP1qFX0T9o893Df3s5NZveAls58ERDh+EcvRzfydKOOXnzFZX6XAwU5PS4b/G91lch5ZM0MKqwa95hPbCMj0ZE094FTpn9yUq6m9xQmG75HD5chEBTF8QjrHcKqg="
    before_install:
    - cd frontend
    install:
    - npm install
    script:
    - "./node_modules/.bin/eslint src/"
    - yarn test --coverage --watchAll=false
    - sonar-scanner
